---
- name: Install telegraf agent/collector (RedHat)
  yum:
    name: "{{ wavefront_collector }}"
    state: "{{ wavefront_pkg_state }}"
    update_cache: yes
  when: ansible_os_family == "RedHat" and wavefront_install_collector == "true" and wavefront_collector == "telegraf"
  register: result
  until: result.rc == 0
  tags:
   - install
   - redhat
   - collector

- name: Install telegraf agent/collector (Ubuntu)
  apt:
    name: "{{ wavefront_collector }}"
    state: "{{ wavefront_pkg_state }}"
    force: 'yes'
    update_cache: yes
  when: ansible_distribution == "Ubuntu" and wavefront_install_collector == "true" and wavefront_collector == "telegraf"
  register: result
  until: result|succeeded
  tags:
   - install
   - debian
   - collector

- name: Overwrite main telegraf.conf file with WF custom config 
  template:
    src: telegraf.conf.wfcopy.j2
    dest: "{{ telegraf_main_config }}"
    mode: 0644
  when: wavefront_install_collector == "true" and wavefront_collector == "telegraf"
  notify: restart telegraf
  tags:
   - install
   - redhat
   - debian
   - collector
   - configure

- name: Create Wavefront output plugin config 10-wavefront.conf
  template:
    src: 10-wavefront.conf.j2
    dest: "{{ telegraf_wavefront_output_plugin_config }}"
    mode: 0644
  when: wavefront_install_collector == "true" and wavefront_collector == "telegraf"
  notify: restart telegraf
  tags:
   - install
   - redhat
   - debian
   - collector
   - configure

- name: Create Telegraf additional plugins file
  template:
    src: telegraf-custom-host-services-processes.conf.j2
    dest: "{{ telegraf_custom_plugins_conf_file }}"
    mode: 0644
    owner: root
    group: root
  when: wavefront_install_collector == "true" and wavefront_collector == "telegraf"
  notify: restart telegraf
  tags:
   - install
   - redhat
   - debian
   - collector
   - configure
